'use client';

import { useState } from 'react';
import { 
  Copy, 
  Check, 
  Share2, 
  Lightbulb, 
  RotateCcw, 
  Target 
} from 'lucide-react';
import { SavedResult } from '@/utils/db';

interface SensitivityDashboardProps {
  result: SavedResult;
}

type TabType = 'camera' | 'ads' | 'gyro' | 'adsGyro';

interface ScopeState {
  no_scope_3rd: number;
  no_scope_1st: number;
  red_dot: number;
  scope_2x: number;
  scope_3x: number;
  scope_4x: number;
  scope_6x: number;
  scope_8x: number;
}

export default function SensitivityDashboard({ result }: SensitivityDashboardProps) {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedConfig, setCopiedConfig] = useState(false);
  const [activeAnalysisTab, setActiveAnalysisTab] = useState<TabType>('camera');

  // Editable sensitivity values initialized from server calculated settings
  const [sensValues, setSensValues] = useState<{
    camera: ScopeState;
    ads: ScopeState;
    gyro: ScopeState | null;
    adsGyro: ScopeState | null;
  }>(() => {
    const initCategory = (catValues: any) => {
      if (!catValues) return null;
      return {
        no_scope_3rd: catValues.no_scope,
        no_scope_1st: catValues.no_scope,
        red_dot: catValues.red_dot,
        scope_2x: catValues.scope_2x,
        scope_3x: catValues.scope_3x,
        scope_4x: catValues.scope_4x,
        scope_6x: catValues.scope_6x,
        scope_8x: catValues.scope_8x,
      };
    };

    return {
      camera: initCategory(result.values.camera)!,
      ads: initCategory(result.values.ads)!,
      gyro: initCategory(result.values.gyro),
      adsGyro: initCategory(result.values.adsGyro),
    };
  });

  const hasGyro = result.inputs.gyroMode !== 'off';

  // Handle slider updates
  const handleSliderChange = (category: TabType, scopeKey: string, val: number) => {
    setSensValues((prev) => {
      const updated = { ...prev };
      if (updated[category]) {
        (updated[category] as any)[scopeKey] = val;
      }
      return updated;
    });
  };

  // Reset entire category/card to server calculated default
  const handleResetCategory = (category: TabType) => {
    setSensValues((prev) => {
      const updated = { ...prev };
      const defaultCat = (result.values as any)[category];
      if (defaultCat) {
        updated[category] = {
          no_scope_3rd: defaultCat.no_scope,
          no_scope_1st: defaultCat.no_scope,
          red_dot: defaultCat.red_dot,
          scope_2x: defaultCat.scope_2x,
          scope_3x: defaultCat.scope_3x,
          scope_4x: defaultCat.scope_4x,
          scope_6x: defaultCat.scope_6x,
          scope_8x: defaultCat.scope_8x,
        };
      }
      return updated;
    });
  };

  // Check if a category has been modified from default
  const isCategoryModified = (category: TabType) => {
    const current = sensValues[category];
    const defaultCat = (result.values as any)[category];
    if (!current || !defaultCat) return false;
    return (
      current.no_scope_3rd !== defaultCat.no_scope ||
      current.no_scope_1st !== defaultCat.no_scope ||
      current.red_dot !== defaultCat.red_dot ||
      current.scope_2x !== defaultCat.scope_2x ||
      current.scope_3x !== defaultCat.scope_3x ||
      current.scope_4x !== defaultCat.scope_4x ||
      current.scope_6x !== defaultCat.scope_6x ||
      current.scope_8x !== defaultCat.scope_8x
    );
  };

  // Copy share link
  const copyShareLink = () => {
    const url = window.location.href;
    navigator.clipboard.writeText(url);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  // Copy config settings block
  const copyConfigText = () => {
    let text = `=== AimSync Sensitivity Configuration ===\n`;
    text += `Device: ${result.inputs.deviceTier.toUpperCase()} | FPS: ${result.inputs.fps} | Finger Layout: ${result.inputs.fingerCount} Fingers\n`;
    text += `Combat Playstyle: ${result.inputs.playstyle.toUpperCase()} | Corrective Tuning: ${result.inputs.primaryProblem.toUpperCase()}\n\n`;

    const formatBlock = (title: string, values: ScopeState | null) => {
      if (!values) return '';
      let block = `[${title} Sensitivity]\n`;
      block += `3rd Person No Scope: ${values.no_scope_3rd}%\n`;
      block += `1st Person No Scope: ${values.no_scope_1st}%\n`;
      block += `Red Dot, Holo, Aim Assist: ${values.red_dot}%\n`;
      block += `2x Scope: ${values.scope_2x}%\n`;
      block += `3x Scope: ${values.scope_3x}%\n`;
      block += `4x Scope: ${values.scope_4x}%\n`;
      block += `6x Scope: ${values.scope_6x}%\n`;
      block += `8x Scope: ${values.scope_8x}%\n\n`;
      return block;
    };

    text += formatBlock('Camera', sensValues.camera);
    text += formatBlock('ADS (Firing)', sensValues.ads);
    if (sensValues.gyro) text += formatBlock('Gyroscope', sensValues.gyro);
    if (sensValues.adsGyro) text += formatBlock('ADS Gyroscope', sensValues.adsGyro);

    text += `Generated by AimSync Configurator`;

    navigator.clipboard.writeText(text);
    setCopiedConfig(true);
    setTimeout(() => setCopiedConfig(false), 2000);
  };

  // Get explanation text for active analysis tab
  const getActiveExplanation = () => {
    switch (activeAnalysisTab) {
      case 'camera':
        return result.explanations.camera_explanation;
      case 'ads':
        return result.explanations.ads_explanation;
      case 'gyro':
        return result.explanations.gyro_explanation || 'Gyroscope is disabled.';
      case 'adsGyro':
        return result.explanations.ads_gyro_explanation || 'Gyroscope is disabled.';
      default:
        return '';
    }
  };

  // Render a PUBG-style sensitivity card containing two columns of sliders (Exact Replica)
  const renderSensCard = (
    category: TabType,
    title: string,
    desc: string,
    maxVal: number
  ) => {
    const values = sensValues[category];
    if (!values) return null;

    const modified = isCategoryModified(category);

    const renderSlider = (scopeKey: string, label: string) => {
      const currentVal = (values as any)[scopeKey];
      const pct = ((currentVal - 1) / (maxVal - 1)) * 100;

      return (
        <div key={scopeKey} className="space-y-2">
          {/* Label Row */}
          <div className="flex justify-between items-center">
            <span className="text-[13px] font-normal text-[#e2e8f0] font-body select-none">
              {label}
            </span>
            <span className="text-[13px] font-semibold text-[#e2e8f0] font-body select-none">
              {currentVal}%
            </span>
          </div>

          {/* Controls Row */}
          <div className="slider-container flex items-center gap-3">
            {/* Minus Button */}
            <button
              onClick={() => handleSliderChange(category, scopeKey, Math.max(1, currentVal - 1))}
              className="control-btn w-8 h-8 bg-[#121d28] border border-white/20 text-white hover:bg-[#1a2b3c] active:bg-[#2a3b4d] flex items-center justify-center font-normal rounded-none cursor-pointer select-none transition-all text-lg"
            >
              −
            </button>

            {/* Slider track container */}
            <div className="slider-track flex-grow h-1 bg-[#0d161f] relative flex items-center">
              <input
                type="range"
                min="1"
                max={maxVal}
                value={currentVal}
                onChange={(e) => handleSliderChange(category, scopeKey, Number(e.target.value))}
                className="pubg-slider"
                style={{
                  background: `linear-gradient(to right, #4a6375 0%, #4a6375 ${pct}%, #0d161f ${pct}%, #0d161f 100%)`
                }}
              />
            </div>

            {/* Plus Button */}
            <button
              onClick={() => handleSliderChange(category, scopeKey, Math.min(maxVal, currentVal + 1))}
              className="control-btn w-8 h-8 bg-[#121d28] border border-white/20 text-white hover:bg-[#1a2b3c] active:bg-[#2a3b4d] flex items-center justify-center font-normal rounded-none cursor-pointer select-none transition-all text-lg"
            >
              +
            </button>
          </div>
        </div>
      );
    };

    return (
      <div className="settings-overlay bg-[#1b2836]/85 border border-white/10 backdrop-blur-[4px] rounded-none p-6 md:p-8 space-y-6 shadow-2xl relative">
        <div className="flex justify-between items-start">
          <div>
            <h3 className="header-title text-[16px] font-medium text-white font-body select-none mb-1">
              {title}
            </h3>
            <p className="header-desc text-[11px] text-[#cbd5e1] mt-0.5 select-none leading-relaxed">
              {desc}
            </p>
          </div>
          {modified && (
            <button
              onClick={() => handleResetCategory(category)}
              className="text-[9px] font-technical text-primary-yellow hover:underline flex items-center gap-1 cursor-pointer"
              title="Reset entire card to optimal default values"
            >
              <RotateCcw className="w-2.5 h-2.5" />
              RESET CARD
            </button>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8">
          {/* Left Column */}
          <div className="space-y-8">
            {renderSlider('no_scope_3rd', '3rd Person No Scope')}
            {renderSlider('red_dot', 'Red Dot, Holographic, Aim Assist')}
            {renderSlider('scope_3x', '3x Scope, Win94')}
            {renderSlider('scope_6x', '6x Scope')}
          </div>

          {/* Right Column */}
          <div className="space-y-8">
            {renderSlider('no_scope_1st', '1st Person No Scope')}
            {renderSlider('scope_2x', '2x Scope')}
            {renderSlider('scope_4x', '4x Scope, VSS')}
            {renderSlider('scope_8x', '8x Scope')}
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-6">
      {/* Action Buttons Header */}
      <div className="flex flex-col sm:flex-row gap-3">
        <button
          onClick={copyConfigText}
          className="flex-1 bg-primary-yellow text-background font-headline font-bold py-3.5 px-4 rounded-xl flex items-center justify-center gap-2.5 shadow-[0_4px_16px_rgba(255,215,0,0.25)] hover:bg-white active:scale-95 transition-all text-base border border-primary-yellow/20 cursor-pointer"
        >
          {copiedConfig ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
          {copiedConfig ? 'COPIED CONFIGURATION!' : 'COPY ALL CONFIG'}
        </button>

        <button
          onClick={copyShareLink}
          className="flex-1 bg-surface-card hover:bg-surface-hover text-foreground font-headline font-bold py-3.5 px-4 rounded-xl flex items-center justify-center gap-2.5 border border-border-tactical/40 active:scale-95 transition-all text-base cursor-pointer"
        >
          {copiedLink ? <Check className="w-5 h-5 text-primary-yellow" /> : <Share2 className="w-5 h-5" />}
          {copiedLink ? 'LINK COPIED!' : 'COPY SHARE LINK'}
        </button>
      </div>

      {/* Dynamic Tactical Analysis Panel with Sub-Tabs */}
      <div className="bg-[#1b2836]/75 border border-[#384b5c]/40 rounded-sm p-5 space-y-4 shadow-2xl relative">
        <div className="flex border-b border-[#384b5c]/30 pb-2 overflow-x-auto no-scrollbar gap-2">
          <div className="bg-primary-yellow/15 p-1 rounded-lg h-fit text-primary-yellow flex-shrink-0 mr-1 animate-pulse">
            <Lightbulb className="w-4 h-4" />
          </div>
          {[
            { id: 'camera', label: 'LOOK ANALYSIS' },
            { id: 'ads', label: 'ADS RECOIL ANALYSIS' },
            { id: 'gyro', label: 'GYRO ANALYSIS', show: hasGyro },
          ].map(
            (tab) =>
              (tab.show !== false) && (
                <button
                  key={tab.id}
                  onClick={() => setActiveAnalysisTab(tab.id as TabType)}
                  className={`text-[10px] font-headline font-bold tracking-widest px-2.5 py-1 transition-all rounded cursor-pointer ${
                    activeAnalysisTab === tab.id
                      ? 'bg-primary-yellow/20 text-primary-yellow border border-primary-yellow/30'
                      : 'text-[#a0b0c0] hover:text-foreground border border-transparent'
                  }`}
                >
                  {tab.label}
                </button>
              )
          )}
        </div>
        <div className="space-y-1">
          <p className="text-xs text-[#a0b0c0] leading-relaxed select-none">
            {getActiveExplanation()}
          </p>
        </div>
      </div>

      {/* PUBG Mobile Themed Sensitivity Cards Stack (Exact Replica) */}
      <div className="space-y-5">
        {renderSensCard(
          'camera', 
          'Camera', 
          '(Affects the sensitivity of the camera when the screen is swiped without firing.)', 
          200
        )}
        
        {renderSensCard(
          'ads', 
          'ADS Sensitivity', 
          '(Affects the sensitivity of the camera when the screen is swiped while firing. Can be used to keep the barrel down.)', 
          200
        )}

        {hasGyro && renderSensCard(
          'gyro', 
          'Gyroscope', 
          '(When the Gyroscope is activated, the sensitivity of the tilt camera controls can be adjusted.)', 
          400
        )}

        {hasGyro && renderSensCard(
          'adsGyro', 
          'ADS Gyroscope', 
          '(When the Gyroscope is activated, the sensitivity of the tilt camera controls during shooting can be adjusted.)', 
          400
        )}
      </div>

      {/* Shooting Range Simulator (Coming Soon Placeholder) */}
      <div className="bg-[#1b2836]/75 border border-[#384b5c]/40 rounded-sm p-5 space-y-4 relative overflow-hidden">
        <div className="flex justify-between items-center border-b border-[#384b5c]/30 pb-2">
          <h3 className="font-headline text-base font-extrabold text-[#9cd8ff] tracking-wide uppercase flex items-center gap-2">
            <Target className="w-5 h-5 text-primary-yellow animate-pulse" />
            SHOOTING RANGE SIMULATOR
          </h3>
          <span className="font-technical text-[9px] bg-primary-yellow/15 text-primary-yellow border border-primary-yellow/30 px-2.5 py-0.5 rounded tracking-widest font-black">
            COMING SOON
          </span>
        </div>

        <div className="relative border border-[#384b5c]/20 rounded-xl bg-background/20 p-8 text-center flex flex-col items-center justify-center min-h-[200px] overflow-hidden">
          <div className="absolute inset-0 opacity-[0.03] pointer-events-none bg-[linear-gradient(to_right,#ffd700_1px,transparent_1px),linear-gradient(to_bottom,#ffd700_1px,transparent_1px)] bg-[size:15px_15px]" />
          
          <div className="relative z-10 space-y-3 max-w-sm">
            <div className="mx-auto w-12 h-12 rounded-full border border-primary-yellow/20 bg-primary-yellow/5 flex items-center justify-center text-primary-yellow mb-2 animate-pulse">
              <Target className="w-6 h-6" />
            </div>
            <h4 className="font-headline text-sm font-extrabold text-foreground tracking-wider uppercase">PHYSICS ENGINE CALIBRATION</h4>
            <p className="text-xs text-[#a0b0c0] leading-relaxed">
              Our interactive 3D weapon recoil simulator is currently undergoing server-side physics engine calibration. Check back soon to test your sensitivity configurations.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
