import type { Metadata } from 'next';
import AdUnit from '@/components/AdUnit';

export const metadata: Metadata = {
  title: "Disclaimer — AimSync PUBG/BGMI Sensitivity Configurator",
  description: "Read our disclaimer regarding non-affiliation with Krafton or Tencent, and guidelines on sensitivity calibration outcomes.",
  alternates: {
    canonical: "https://www.gamingsensi.site/disclaimer",
  },
  openGraph: {
    title: "Disclaimer — AimSync PUBG/BGMI Sensitivity Configurator",
    description: "Read our disclaimer regarding non-affiliation with Krafton or Tencent, and guidelines on sensitivity calibration outcomes.",
  },
};

export default function Disclaimer() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-16 text-white font-body text-base leading-relaxed space-y-8">
      <div>
        <h1 className="text-4xl font-headline font-black text-primary-yellow uppercase tracking-wider mb-2">
          Legal Disclaimer
        </h1>
        <p className="text-xs text-text-muted uppercase tracking-widest font-technical">
          Last Updated: July 2026 • AimSync Compliance
        </p>
      </div>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white uppercase tracking-tight">
          1. Brand Non-Affiliation Disclosure
        </h2>
        <p>
          AimSync is an independent, community-driven esports utility website. We are <strong>not</strong> affiliated, associated, authorized, endorsed by, or in any way officially connected with:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-[#cbdbe6]">
          <li><strong>Krafton Inc.</strong> (Developers/Publishers of Battlegrounds Mobile India - BGMI).</li>
          <li><strong>Tencent Games / LightSpeed & Quantum Studio</strong> (Developers/Publishers of PUBG Mobile).</li>
          <li><strong>PUBG Corporation / Krafton</strong> (Owners of the PUBG IP).</li>
        </ul>
        <p>
          The names &ldquo;PUBG Mobile,&rdquo; &ldquo;BGMI,&rdquo; &ldquo;Battlegrounds Mobile India,&rdquo; as well as related logos, gear designations, maps, and specific game modes are registered trademarks of their respective owners. Their use on this website is strictly for informational, educational, and analytical purposes under fair use policies. <strong>AimSync does not claim ownership over any registered trademarks, copyrighted material, or game assets referenced on this platform.</strong>
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white uppercase tracking-tight">
          2. Aiming Sensitivity Results Disclaimer
        </h2>
        <p>
          The sensitivity configurations, scope multipliers, and layout maps generated by our online calibration tool are <strong>provided strictly for informational, educational, and entertainment purposes</strong>.
        </p>
        <p>
          <strong>No outcome is guaranteed.</strong> Aiming and recoil control in mobile first-person and third-person shooters are heavily dependent on individual player reaction times, hand-eye coordination, muscle memory, device condition, network ping (latency), and physical setup (such as the friction coefficient of screen protectors). Implementing these settings does not guarantee an increase in rank, kill-to-death (K/D) ratio, or target accuracy.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white uppercase tracking-tight">
          3. Technical Hardware & Software Liability
        </h2>
        <p>
          AimSync provides device-lookup specs for informational purposes only. We are not responsible or liable for any device issues, heating, thermal throttling, screen wear, gyroscope sensor drift, or account-related actions resulting from adjusting game settings. Adjusting your device settings or modifying your in-game layout is done entirely at your own risk.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white uppercase tracking-tight">
          4. Contact & Compliance Inquiries
        </h2>
        <p>
          If you have any questions regarding this disclaimer, trademark usage, or wish to submit feedback regarding our calculations, please contact us directly:
        </p>
        <div className="bg-[#1b2836]/75 border border-[#384b5c]/40 rounded-xl p-6">
          <p className="font-technical uppercase text-sm text-primary-yellow">
            AimSync Compliance Operations
          </p>
          <p className="text-sm mt-1">
            Email: <a href="mailto:adnanchy083@gmail.com" className="underline hover:text-white transition-colors">adnanchy083@gmail.com</a>
          </p>
        </div>
      </section>
      
      <AdUnit slot="8085223740" format="auto" className="mt-8" />
    </main>
  );
}
